export const urlLogin = 'http://localhost:3000/login'
export const urlCatalogItems = 'http://localhost:3000/articles'
// export const URLlogout = 'http://localhost:3000/logout'
// export const URLcatalogItems = 'http://localhost:3000/articles'
// export const URLidItem = 'http://localhost:3000/'